### PR TITLE
Fix character transparency

### PR DESCRIPTION
**Pull request by CoderPuppy**

### CODE REVIEW

**Comment by hbomb79** [comment]
7d87b4b is what I am looking at and getting a bit confused. Wouldn't it be better if we kept the use of `self.backgroundChar` to dictate transparency.

Something like this would work the same
`local pixel = { self.backgroundChar, self.colour, not self.backgroundChar and 0 or colour or self.backgroundColour }`

This has the added benefits of being editable through TML/Theme files (it is applied to the node, not its canvas like `canvas.transparent`) _and_ is one less property to keep track of.

Let me know what you think.

**Comment by CoderPuppy** [comment]
The use case I had in mind for the whole thing is an opaque panel with the text showing through.

this is the test case I've been using:

(created using `backgroundChar = nil` and `backgroundColour = grey`)

If you don't think that'd be useful, then using `backgroundChar` for transparency would be fine (though I think it'd still be better to have `transparency`).
Otherwise we should just add `transparency` to `Component`.

**Comment by hbomb79** [comment]
I see that being useful, what I don't see is the reason why we can't use `backgroundChar = nil` to dictate transparency, if that example _is_ using background char nil.

**Comment by CoderPuppy** [comment]
but what do you mean by transparency there?
I've been designing around two notions of transparency char (`backgroundChar = nil`) and background (`backgroundColor = 0`) (also `backgroundTextColor` which is used when `tc == nil`)

**Comment by hbomb79** [comment]
What is the difference between `canvas.transparent` and `backgroundChar=nil` and can that difference be eliminated. At this point in time, I have no idea why the two exist as separate entities even though `canvas.transparent` seems to serve one purpose (the char value when clearing the canvas)

**Comment by CoderPuppy** [comment]
`canvas.transparent` is essentially `backgroundChar = nil` and `backgroundColor = 0`, but without things inside inheriting it
This is for context menus, which need to be transparent and have a `backgroundColour` for the subframes to inherit.

**Comment by hbomb79** [comment]
> This is for context menus, which need to be transparent and have a backgroundColour for the subframes to inherit.

The commit you reverted for the context menus seemed to work just fine using `backgroundChar = nil`.

**Comment by CoderPuppy** [comment]
Yes, but it breaks character transparency

**Comment by hbomb79** [comment]
I am confused as to how the change fixes that? The pixel foreground colour is unchanged, right? Wouldn't that mean the problem is in the transparency detection, and not the value of the char/background colour?

**Comment by CoderPuppy** [comment]
88adf9f36abb61d44582a75f08fcbc55d0850715 fixed character transparency
the rest are fixing context menus

**Comment by hbomb79** [comment]
What was wrong with the context menus, they seemed to work fine for me. Did you set different arguments when testing them?

**Comment by CoderPuppy** [comment]
88adf9f36abb61d44582a75f08fcbc55d0850715 also broke context menus

**Comment by hbomb79** [comment]
Ugh.

**Comment by hbomb79** [comment]
If this change is made
> local pixel = { self.backgroundChar, self.colour, not self.backgroundChar and 0 or colour or self.backgroundColour }

What actually goes wrong, and why can't it be adjusted to function correctly?

**Comment by CoderPuppy** [comment]
then context menus' subframes need another way of getting a background

**Comment by hbomb79** [comment]
Surely if `backgroundChar` is `nil`, that should tell the rendering system that the pixel should be transparent... Doesn't that make sense?

**Comment by CoderPuppy** [comment]
completely transparent?
then how you make it only character transparent?

**Comment by hbomb79** [comment]
You would set the color to `0`?

**Comment by CoderPuppy** [comment]
then how do you make it foreground transparent? (forgot about this one earlier)
I don't consider this super useful, do you? we could remove it

**Comment by hbomb79** [comment]
If the foreground is transparent the character would be invisible because all you would see is the background of the pixel. Isn't that how transparency works?

**Comment by hbomb79** [comment]
If both are transparent, the pixel would be invisible... right?

**Comment by CoderPuppy** [comment]
Not with my system...

that's with `colour = 0` and `backgroundColour = grey`

**Comment by hbomb79** [comment]
Is that broken, or intended? I would argue that the character being transparent means all you would see is what is behind it (the background)

**Comment by CoderPuppy** [comment]
That's intended
that `top = { 'o', 0, grey }` and `bot = { ' ', orange, orange }` to `new = {'o', orange, grey}`
if you don't want a character then you'd use `' '`

**Comment by hbomb79** [comment]
Yeah, that makes sense. I still don't understand why the `transparent` property is needed. Surely if `backgroundChar = nil` that means "no pixel here"?

Are you saying that `backgroundChar = nil` means inherit the character from underneath?

**Comment by CoderPuppy** [comment]
well really `backgroundChar` is just used for clearing but essentially yes

**Comment by hbomb79** [comment]
Jeez I am so dense. I see the purpose now, sorry for the confusion.

**Comment by CoderPuppy** [comment]
No problem, I'm pretty sure I was explaining from the point of view of "you've read the code, now you obviously instantly understand all the implications of it"

**Pull request merged**
